### ISSUE TITLE
Support for Capacitor 3 and/or Angular 11?

### ISSUE THREAD

**Issue by nunoarruda** [ionic-team/capacitor-angular-toolkit#12]
If I follow the [Angular & Capacitor](https://capacitorjs.com/solution/angular) instructions, I get some weird output when adding the schematics to an Angular 11 CLI project:

```
nunoarruda@nunos-mbp test-app % ng add @capacitor/angular
ℹ Using package manager: npm
✖ Unable to find compatible package.  Using 'latest'.
✖ Package has unmet peer dependencies. Adding the package may not succeed.
✔ Package successfully installed.
UPDATE package.json (1309 bytes)
UPDATE src/app/app.component.ts (256 bytes)
✔ Packages installed successfully.
error: unknown option '--npm-client'
nunoarruda@nunos-mbp test-app % 
```
Maybe this schematic needs to be updated for Capacitor 3 and/or for Angular 11?

I'm on macOS Big Sur 11.4, node v14.17.0, npm 6.14.13, Angular 11.x.

**Comment by MNorgren** [comment]
I am also needing support for angular 11 (and angular 12 would be nice as well).

I have been using angular 11, but continually have to force npm install due to rxjs version mismatches:

```
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"~6.4.0" from @capacitor/angular@1.0.3
npm ERR! node_modules/@capacitor/angular
npm ERR!   @capacitor/angular@"^1.0.3" from the root project
```

**Comment by syslogic** [comment]
Think I've filed a duplicate bug, with some more details.
Just forked the repo and will try to update dependencies.
