### ISSUE TITLE
Capacitor could not find the web assets directory

### ISSUE THREAD

**Issue by JAspeling** [ionic-team/capacitor-angular-toolkit#6]
I'm trying to add capacitor to my web app - but when running `npx cap add android`  I get the following error:

> Capacitor could not find the web assets directory "C:\Source\Upwork\snabvendor\snabvendor\www".
    Please create it and make sure it has an index.html file. You can change
    the path of this directory in capacitor.config.json (webDir option).
    You may need to compile the web assets for your app (typically 'npm run build').
    More info: https://capacitorjs.com/docs/basics/building-your-app

I have built my app, but with Angular it's output is the `/dist/<project-name>` folder. Should the "webDir" in the `capacitor.config.json` point to this folder instead of `www`?

**Comment by thomasgainant** [comment]
The error says exactly what you need to do: go in your capacitor.config.json and change the webDir property to make point to the index.html generated using ng build. So as you said, change it to /dist/xxxxx. I had the same problem and it solved it.

**Comment by jcesarmobile** [comment]
Capacitor 3 automatically detects the framework and set the webDir accordingly.

I've tested with [this changes](https://github.com/ionic-team/capacitor-angular-toolkit/pull/21) that add Capacitor 3 support and it set the webDir properly
